// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prxezdkgejtyglwxiule.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByeGV6ZGtnZWp0eWdsd3hpdWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzMzNTksImV4cCI6MjA3MjMwOTM1OX0.6pKx0DwmCCCkN-EgB1zVH1K2MiG58X3neX24Dss44ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});